services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "10090:8080"
    environment:
      - HTTP_PROXY=${PROXY_BRIDGE}
      - HTTPS_PROXY=${PROXY_BRIDGE}
      # - WATCHTOWER_NOTIFICATIONS=email
      # - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${EMAIL_FROM}
      # - WATCHTOWER_NOTIFICATION_EMAIL_TO=${EMAIL_TO}
      # - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${EMAIL_SERVER}
      # - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=${EMAIL_SERVER_PORT}
      # - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${EMAIL_SERVER_USER}
      # - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${EMAIL_SERVER_PASSPORT}
      - WATCHTOWER_HTTP_API_UPDATE=true
      - WATCHTOWER_HTTP_API_PERIODIC_POLLS=true
      - WATCHTOWER_HTTP_API_METRICS=true
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_HTTP_API_TOKEN}
      - TZ=Asia/Shanghai
      - WATCHTOWER_SCHEDULE=0 0 0 * * *
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_REMOVE_VOLUMES=true
      # - DOCKER_API_VERSION=1.52

  peerbanhelper:
    image: "ghostchu/peerbanhelper:latest"
    restart: unless-stopped
    container_name: "peerbanhelper"
    volumes:
      - ${DOCKER_VOLUME}/peerbanhelper:/app/data
    ports:
      - "10225:9898"
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=Asia/Shanghai

  ani-rss:
    container_name: ani-rss
    volumes:
      - ${DOCKER_VOLUME}/ani-rss/config:/config
      - /mnt/smb/downloads/auto:/downloads/auto
      - /mnt/smb/downloads/manual:/downloads/manual
      - /mnt/smb/media/anime:/anime
      - /mnt/smb/media/movies:/movie
      - /mnt/smb/media/shows:/show
    ports:
      - 10230:7789
    environment:
      - PORT=7789
      - CONFIG=/config
      - TZ=Asia/Shanghai
    restart: unless-stopped
    image: wushuo894/ani-rss

  # mc:
  #   container_name: mc
  #   image: itzg/minecraft-server
  #   restart: unless-stopped
  #   tty: true
  #   stdin_open: true
  #   ports:
  #     - "11000:25565"
  #   environment:
  #     EULA: "TRUE"
  #     # ONLINE_MODE: false
  #     TYPE: PAPER
  #     VERSION: 1.20.1
  #     # HTTP_PROXY=${PROXY_BRIDGE}
  #     # HTTPS_PROXY=${PROXY_BRIDGE}
  #   volumes:
  #     # attach the relative directory 'data' to the container's /data path
  #     - ${DOCKER_VOLUME}/mc/paper-1.20.1-vanilla/data:/data
  #
  # natfrp-service:
  #   image: natfrp.com/launcher
  #   container_name: natfrp-service
  #   restart: unless-stopped
  #   network_mode: host
  #   volumes:
  #     - ${DOCKER_VOLUME}/natfrp-service:/run
  #   environment:
  #     NATFRP_TOKEN: ${NATFRP_TOKEN}
  #     NATFRP_REMOTE: ${NATFRP_REMOTE}
  #     TZ: Asia/Shanghai
  #
  # napcat:
  #   environment:
  #     - NAPCAT_UID=${UID}
  #     - NAPCAT_GID=${GID}
  #   network_mode: bridge
  #   ports:
  #     - 3000:3000
  #     - 3001:3001
  #     - 6099:6099
  #   volumes:
  #     - ${DOCKER_VOLUME}/napcat/config:/app/napcat/config
  #     - /home/howl/repo/qbot/downloads:/home/howl/repo/qbot/downloads
  #   container_name: napcat
  #   restart: unless-stopped
  #   image: mlikiowa/napcat-docker:latest
